name: Docker Image CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main,master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: git checkout repository
      run:  git clone https://github.com/MinterTeam/minter-hub.git && rm -rf src && mv minter-hub src
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag urpyllika/minter-hub:$(cd src/ && git log --format="%H" -n 1)
    - name: Push the Docker image
      run: docker push urpyllika/minter-hub:$(cd src/ && git log --format="%H" -n 1)
