name: Docker Image CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main,master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update submodules recursive
      run: git submodule update --recursive
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag urpyllika/minter-hub:$(cd src/ && git log --format="%H" -n 1)
    - name: docker login
      run: docker login --username=urpyllika
    - name: Build the Docker image
      run: docker push urpyllika/minter-hub:$(cd src/ && git log --format="%H" -n 1)
    - name: docker logoff
      run: docker logout
