name: Docker Image CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main,master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get commit version
      run: GIT_COMMIT=$(cd src/ && git log --format="%H" -n 1)
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag urpyllika/minter-hub:$GIT_COMMIT -v src:/src
    - name: Build the Docker image
      run: docker push urpyllika/minter-hub:$GIT_COMMIT
